name: fcest-env
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - cmake
  - git
  - jupyter
  # - jupyterlab
  # - matplotlib
  - mpfr  # for installing R package `rmgarch` on Ubuntu
  # - networkx
  - packaging
  - pip
  - python=3.10
  - pyyaml
  - r-base=4.1.0
  - r-gmp  # for installing R package `rmgarch` on Ubuntu
  - statsmodels
  - tabulate
  - typing-extensions
  - tzlocal
  - pip:
    # - bctpy  # Brain Connectivity Toolbox
    # - hcp_utils
    - nibabel==5.1.0
    - nilearn==0.10.1
    - nipype
    - numpy==1.23.5
    - pandas==1.5.3
    - pingouin==0.5.3
    - ptitprince==0.2.6
    - ruff
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - seaborn==0.11.0
    - tensorflow==2.11.0
    # - templateflow
    - tensorflow_probability==0.19.0
    - git+https://github.com/OnnoKampman/FCEst@v0.1.0
    # - git+https://github.com/RittmanResearch/maybrain@master
